### ISSUE TITLE
trackPerformance function

### ISSUE THREAD

**Issue by thecloudtechnologist** [bennivalur/theFPLBot#4]
Should this function look this way? 

`def trackPerformance(teamToGet,week):

    with open('data/performanceTracking/overallTrack.json','r') as overalltrack:
        overalltrack = json.load(overalltrack)

    if overalltrack['entry_history']['event'] < week-1:`

it is currently as 
`def trackPerformance(teamToGet,week):

    with open('data/performanceTracking/overallTrack.json','r') as overalltrack:
        overalltrack = json.load(overalltrack)

    if overalltrack[-1]['event'] < week-1:`

and also the 'ppp' values seems to be too high(unrealistic)

**Comment by bennivalur** [comment]
Yes, It is supposed to be an array of events (week1, week2, etc) without the player picks. Basically to just track overall rank development over time. I debated including the team picks or not and settled on not. Do you think it would be better to include it?

I had not noticed the ppp but I do feel some players are way over projected this week. So I am looking into that.

**Comment by bennivalur** [comment]
@thecloudtechnologist I can confirm that there is a problem in the scoring projection calculator.  Fix should be pushed tonight

**Comment by thecloudtechnologist** [comment]
Cheers! 

have to make the following changes for that to work. 
`trackPerformance.py`

<hr>

```import copy
import json,urllib
import itertools

def trackPerformance(teamToGet,week):

    with open('data/performanceTracking/overallTrack.json','r') as overalltrack:
        overalltrack = json.load(overalltrack)

    if overalltrack['entry_history']['event'] < week-1:
        
            print("Getting Event Entry")
            urllink = "https://fantasy.premierleague.com/api/entry/"+ str(teamToGet) +"/event/"+ str(week-1) +"/picks/"
            
            with urllib.request.urlopen(urllink) as url:
                data = json.loads(url.read().decode())
                
                overalltrack.update(data['entry_history'])

                with open('data/performanceTracking/overallTrack.json', 'w') as file:
                    file.write(json.dumps(overalltrack))      
        
    else:
        print("Latest Track already on file")
    #TODO make a trend graphic or something```
